### ISSUE TITLE
UnivTransferType enum doesn't support MAIN_FUNDING and FUNDING_MAIN types

### ISSUE THREAD

**Issue by namig** [binance/binance-connector-typescript#11]
Add universal transfer type `MAIN_FUNDING` and `FUNDING_MAIN` from documentation https://binance-docs.github.io/apidocs/spot/en/#user-universal-transfer-user_data.

Fix: https://github.com/binance/binance-connector-typescript/pull/10

**Comment by alplabin** [comment]
The fix has been added to the latest release.
