### ISSUE TITLE
Combination of optional parameters invalid. Recommendation: 'symbol' and 'symbols' cannot both be sent.

### ISSUE THREAD

**Issue by wu985215993** [binance/binance-connector-typescript#16]
Hello, I encountered a problem when calling the getTradingDay method of the REST API. When I pass both the symbol and symbols parameters under the options, it throws an error:

`Combination of optional parameters invalid. Recommendation: 'symbol' and 'symbols' cannot both be sent.`
However, if I only pass the symbols parameter without symbol, it throws the following error:

```
Error: Missing Parameters
    at validateRequiredParameters (/root/stickerwu-projects/stickerwu-binance-api/node_modules/.pnpm/@binance+connector-typescript@0.3.6/node_modules/@binance/connector-typescript/src/helpers/utils.ts:73:37)
```
Below is my code:
```
@Post('getTradingDay')
  /** 获取交代币易日行情(Ticker) */
  async getTradingDay(
    @Body() body: GetTradingDayParamType,
  ): Promise<TradingDayTickerResponse | TradingDayTickerResponse[]> {
    const options: TradingDayTickerOptions = body.options && {
      ...body.options,
      symbols: body.options.symbols && JSON.stringify(body.options.symbols),
    };
    console.log(body, options);

    return await this.marketService.getTradingDay(body.symbol, options);
  }
  /** 获取交代币易日行情(Ticker) */
  async getTradingDay(
    symbol: string,
    options?: TradingDayTickerOptions,
  ): Promise<TradingDayTickerResponse | TradingDayTickerResponse[]> {
    return await this.client.tradingDayTicker(symbol, options);
  }

```

It seems that there is an issue with the combination of optional parameters symbol and symbols. According to the error message, it's recommended not to send both symbol and symbols at the same time.

However, when I only pass symbols and omit symbol, it still throws an error indicating missing parameters.

Could you please provide guidance on how to resolve this issue? Thank you!

**Comment by alplabin** [comment]
Hey, you are correct. There's an issue with the combination of optional parameters symbol and symbols. 
We will work on fixing that.
