### ISSUE TITLE
permissionSets not added to typings of Exchange Information

### ISSUE THREAD

**Issue by abanchev** [binance/binance-connector-typescript#24]
The permissions changed, the api should reflect the breaking changes
https://developers.binance.com/docs/binance-spot-api-docs/CHANGELOG

**Comment by alplabin** [comment]
This has been updated in the latest release: https://github.com/binance/binance-connector-typescript/pull/28/files#diff-7f867692b617f84c9b19ae22c8b8909d1675c91126af79b6156eb0ad31ff89dd
