### ISSUE TITLE
Multiple subscriptions do not work with more than 2 subscriptions

### ISSUE THREAD

**Issue by abanchev** [binance/binance-connector-typescript#25]
https://github.com/binance/binance-connector-typescript/blob/8d3267389f9cff96863dac09bbee77514ea153ed/src/websocketStream.ts#L23

string.replace replaces only the first occurence of a symbol, so
`sub1,sub2,sub3,sub4` will incorrectly be changed to `sub1/sub2,sub3,sub4`

Better alternative is 
```
 if (Array.isArray(stream)) stream = stream.join("/");
```

**Comment by josbert-m** [comment]
I submitted a new pull request for this in https://github.com/binance/binance-connector-typescript/pull/26
