### ISSUE TITLE
Module has no exported member 'Spot' and 'WebsocketStream'

### ISSUE THREAD

**Issue by mars1211** [binance/binance-connector-typescript#3]
Error
>  TS2305: Module '"@binance/connector-typescript"' has no exported member 'Spot'.

In Example:
`import { Spot } from '@binance/connector-typescript';

const API_KEY = '';
const API_SECRET = '';
const BASE_URL = 'https://api.binance.com';

const client = new Spot(API_KEY, API_SECRET, { baseURL: BASE_URL });
client.exchangeInformation().then((res) => {
    console.log(res);
}).catch(err => { console.log(err) });`

**Comment by chrisyy2003** [comment]
import { Spot } from '@binance/connector-typescript/src/index';

**Comment by 2pd** [comment]
This has been fixed in the latest release.
