### ISSUE TITLE
Dual Investment API is not available

### ISSUE THREAD

**Issue by thanhhoa214** [binance/binance-connector-typescript#30]
Hi team, I looked into Binance API documentation, it has Dual Investment API listed here https://binance-docs.github.io/apidocs/spot/en/#dual-investment-endpoints. But I cannot find the correlative function in this library (I tried searching in `simpleEarn` but not found).
Hope you can help. Thank you!

**Comment by alplabin** [comment]
It has been added in the following release: https://github.com/binance/binance-connector-typescript/releases/tag/v0.3.13
